//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaNGOS_GUI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class hcStringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal hcStringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MaNGOS_GUI.Resources.hcStringResources", typeof(hcStringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a Message to Broadcast..
        /// </summary>
        internal static string broadcastMessage_EnterMessage {
            get {
                return ResourceManager.GetString("broadcastMessage_EnterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account already exists..
        /// </summary>
        internal static string createAccount_AccountExists {
            get {
                return ResourceManager.GetString("createAccount_AccountExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter an account name to continue..
        /// </summary>
        internal static string createAccount_EnterAccountName {
            get {
                return ResourceManager.GetString("createAccount_EnterAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a password to continue..
        /// </summary>
        internal static string createAccount_EnterPassword {
            get {
                return ResourceManager.GetString("createAccount_EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no account by that name in the database..
        /// </summary>
        internal static string deleteAccount_AccountDoesntExist {
            get {
                return ResourceManager.GetString("deleteAccount_AccountDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to delete this account?.
        /// </summary>
        internal static string deleteAccount_ConfirmDelete {
            get {
                return ResourceManager.GetString("deleteAccount_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        internal static string deleteAccount_ConfirmDeleteCaption {
            get {
                return ResourceManager.GetString("deleteAccount_ConfirmDeleteCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an account to delete..
        /// </summary>
        internal static string deleteAccount_EnterAccount {
            get {
                return ResourceManager.GetString("deleteAccount_EnterAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while trying to complete this action..
        /// </summary>
        internal static string Global_CommandError {
            get {
                return ResourceManager.GetString("Global_CommandError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following command was completed successfully: \n{0}.
        /// </summary>
        internal static string Global_CommandSuccesful {
            get {
                return ResourceManager.GetString("Global_CommandSuccesful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not saved any config values. Default values loaded..
        /// </summary>
        internal static string Global_DataAccess_Config_NotSavedAnyConfigValues {
            get {
                return ResourceManager.GetString("Global_DataAccess_Config_NotSavedAnyConfigValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bak files (*.bak)|*.bak|All files (*.*)|*.*.
        /// </summary>
        internal static string Global_DumpFileDialogFilter {
            get {
                return ResourceManager.GetString("Global_DumpFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while connecting to the database. Check your configuration..
        /// </summary>
        internal static string Global_ErrorConnectingDB {
            get {
                return ResourceManager.GetString("Global_ErrorConnectingDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database problem.
        /// </summary>
        internal static string Global_ErrorConnectingDBShort {
            get {
                return ResourceManager.GetString("Global_ErrorConnectingDBShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no character by that name in the database..
        /// </summary>
        internal static string kickCharacter_CharacterDoesntExist {
            get {
                return ResourceManager.GetString("kickCharacter_CharacterDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a charcter to kick from the server..
        /// </summary>
        internal static string kickCharacter_EnterCharacter {
            get {
                return ResourceManager.GetString("kickCharacter_EnterCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no account by that name in the database..
        /// </summary>
        internal static string loadDump_AccountDoesntExist {
            get {
                return ResourceManager.GetString("loadDump_AccountDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a file name to continue..
        /// </summary>
        internal static string loadDump_EnterFileName {
            get {
                return ResourceManager.GetString("loadDump_EnterFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a player name or guid to continue..
        /// </summary>
        internal static string loadDump_EnterNameOrGuid {
            get {
                return ResourceManager.GetString("loadDump_EnterNameOrGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU: (Offline).
        /// </summary>
        internal static string ManguiMain_CpuOffline {
            get {
                return ResourceManager.GetString("ManguiMain_CpuOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days:.
        /// </summary>
        internal static string ManguiMain_Days {
            get {
                return ResourceManager.GetString("ManguiMain_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find mangos.conf file check your GUI config..
        /// </summary>
        internal static string ManguiMain_ErrorMangosConf {
            get {
                return ResourceManager.GetString("ManguiMain_ErrorMangosConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours:.
        /// </summary>
        internal static string ManguiMain_Hours {
            get {
                return ResourceManager.GetString("ManguiMain_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mangos server is not running. Please start mangos first..
        /// </summary>
        internal static string ManguiMain_MangosNotRunning {
            get {
                return ResourceManager.GetString("ManguiMain_MangosNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mangos is already running..
        /// </summary>
        internal static string ManguiMain_MangosRunning {
            get {
                return ResourceManager.GetString("ManguiMain_MangosRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to start mangos server please check your GUI configuration..
        /// </summary>
        internal static string ManguiMain_MangosStartError {
            get {
                return ResourceManager.GetString("ManguiMain_MangosStartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Starting Mangos.
        /// </summary>
        internal static string ManguiMain_MangosStartErrorCaption {
            get {
                return ResourceManager.GetString("ManguiMain_MangosStartErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Now: .
        /// </summary>
        internal static string ManguiMain_Online {
            get {
                return ResourceManager.GetString("ManguiMain_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realm server is not running. Please start realm first..
        /// </summary>
        internal static string ManguiMain_RealmNotRunning {
            get {
                return ResourceManager.GetString("ManguiMain_RealmNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realm is already running..
        /// </summary>
        internal static string ManguiMain_RealmRunning {
            get {
                return ResourceManager.GetString("ManguiMain_RealmRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to start realm server please check your GUI configuration..
        /// </summary>
        internal static string ManguiMain_RealmStartError {
            get {
                return ResourceManager.GetString("ManguiMain_RealmStartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Starting Realm.
        /// </summary>
        internal static string ManguiMain_RealmStartErrorCaption {
            get {
                return ResourceManager.GetString("ManguiMain_RealmStartErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servers not shutdown properly. May need manual shutdown..
        /// </summary>
        internal static string ManguiMain_ServerShutdownError {
            get {
                return ResourceManager.GetString("ManguiMain_ServerShutdownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown Error.
        /// </summary>
        internal static string ManguiMain_ServerShutdownErrorCaption {
            get {
                return ResourceManager.GetString("ManguiMain_ServerShutdownErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  -- Version: .
        /// </summary>
        internal static string ManguiMain_Version {
            get {
                return ResourceManager.GetString("ManguiMain_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a new player limit..
        /// </summary>
        internal static string playerLimit_EnterLimit {
            get {
                return ResourceManager.GetString("playerLimit_EnterLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a character name..
        /// </summary>
        internal static string sendMeassage_EnterCharacter {
            get {
                return ResourceManager.GetString("sendMeassage_EnterCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This character does not exist..
        /// </summary>
        internal static string sendMessage_CharacterDoesntExist {
            get {
                return ResourceManager.GetString("sendMessage_CharacterDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Account:.
        /// </summary>
        internal static string serverBans_CaseAccount {
            get {
                return ResourceManager.GetString("serverBans_CaseAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Character:.
        /// </summary>
        internal static string serverBans_CaseCharacter {
            get {
                return ResourceManager.GetString("serverBans_CaseCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter IP:.
        /// </summary>
        internal static string serverBans_CaseIP {
            get {
                return ResourceManager.GetString("serverBans_CaseIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose type of ban..
        /// </summary>
        internal static string serverBans_ChooseBanType {
            get {
                return ResourceManager.GetString("serverBans_ChooseBanType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose ban or unban first..
        /// </summary>
        internal static string serverBans_ChooseBanUnban {
            get {
                return ResourceManager.GetString("serverBans_ChooseBanUnban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter an account/character/ip depending on type of ban..
        /// </summary>
        internal static string serverBans_EnterAccountCharIP {
            get {
                return ResourceManager.GetString("serverBans_EnterAccountCharIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter reason for ban..
        /// </summary>
        internal static string serverBans_EnterBanReason {
            get {
                return ResourceManager.GetString("serverBans_EnterBanReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter delay time in seconds..
        /// </summary>
        internal static string serverShutdown_EnterDelayTime {
            get {
                return ResourceManager.GetString("serverShutdown_EnterDelayTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account does not exist..
        /// </summary>
        internal static string setBC_AccountUnknown {
            get {
                return ResourceManager.GetString("setBC_AccountUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate BC.
        /// </summary>
        internal static string setBC_Activate {
            get {
                return ResourceManager.GetString("setBC_Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose Activate/Deactivate BC..
        /// </summary>
        internal static string setBC_ChooseAction {
            get {
                return ResourceManager.GetString("setBC_ChooseAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate BC.
        /// </summary>
        internal static string setBC_deactivate {
            get {
                return ResourceManager.GetString("setBC_deactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an account to modify..
        /// </summary>
        internal static string setBC_EnterAccount {
            get {
                return ResourceManager.GetString("setBC_EnterAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account does not exist..
        /// </summary>
        internal static string setGM_AccountUnknown {
            get {
                return ResourceManager.GetString("setGM_AccountUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a GM level..
        /// </summary>
        internal static string setGM_ChooseGMLevel {
            get {
                return ResourceManager.GetString("setGM_ChooseGMLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an account to modify..
        /// </summary>
        internal static string setGM_EnterAccount {
            get {
                return ResourceManager.GetString("setGM_EnterAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a new MOTD..
        /// </summary>
        internal static string SetMOTD_EnterMOTD {
            get {
                return ResourceManager.GetString("SetMOTD_EnterMOTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match or have not been entered..
        /// </summary>
        internal static string setPassword_PasswordNoMatch {
            get {
                return ResourceManager.GetString("setPassword_PasswordNoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no character by the name &quot;{0}&quot; in the database..
        /// </summary>
        internal static string teleChar_BadCharacterName {
            get {
                return ResourceManager.GetString("teleChar_BadCharacterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a character to teleport..
        /// </summary>
        internal static string teleChar_PleaseEnterCharacterToTeleport {
            get {
                return ResourceManager.GetString("teleChar_PleaseEnterCharacterToTeleport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a file name to continue..
        /// </summary>
        internal static string writeDump_EnterFileName {
            get {
                return ResourceManager.GetString("writeDump_EnterFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a player name or guid to continue..
        /// </summary>
        internal static string writeDump_EnterPlayerName {
            get {
                return ResourceManager.GetString("writeDump_EnterPlayerName", resourceCulture);
            }
        }
    }
}
